// TE-IMS-PROC-HSE-008 — TE-IMS-PROC-HSE-008
// Auto-generated from source DOCX. Content is verbatim; only design/format changed.
import { Link } from "wouter";
import Layout from "@/components/Layout";

export default function TE_IMS_PROC_HSE_008() {
  return (
    <Layout>
      {/* ── Document Header ── */}
      <div style={{ backgroundColor: "#081C2E" }} className="relative overflow-hidden">
        <div className="container pt-8 pb-6 relative z-10">
          <div className="flex flex-col gap-3">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs font-bold px-2 py-0.5 rounded" style={{ backgroundColor: "rgba(196,154,40,0.15)", color: "#C49A28" }}>
                  Procedure
                </span>
                <span className="text-xs font-mono" style={{ color: "rgba(255,255,255,0.4)" }}>
                  TE-IMS-PROC-HSE-008
                </span>
              </div>
              <h1 className="text-white text-2xl md:text-3xl font-extrabold leading-tight tracking-tight">
                TE-IMS-PROC-HSE-008
              </h1>
            </div>
            <div className="flex flex-wrap gap-4 mt-1">
              <span className="text-xs" style={{ color: "rgba(255,255,255,0.45)" }}>Rev01</span>
              <span className="text-xs" style={{ color: "rgba(255,255,255,0.45)" }}>True East Mining Company</span>
              <span className="text-xs" style={{ color: "rgba(255,255,255,0.45)" }}>IMS — Procedure</span>
            </div>
          </div>
        </div>
      </div>

      {/* ── Back Navigation ── */}
      <div className="container pt-4 pb-2">
        <Link href="/docs/proc" className="text-xs font-medium hover:underline flex items-center gap-1" style={{ color: "#6b7a8d" }}>
          ← Back to Procedures
        </Link>
      </div>

      {/* ── Document Body ── */}
      <div className="container pb-16">
        <div className="max-w-4xl">


            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>WASTE MANAGEMENT PROCEDURE</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>WASTE MANAGEMENT PROCEDURE</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Document</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>TE-IMS-PROC-HSE-008</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Revision</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>01</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Date</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>10.04.2026</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Status</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Approved for Implementation</td>
                </tr>
                </tbody>
              </table>
            </div>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>1. Purpose</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>To establish a standardised, safe, and environmentally responsible process for identifying, segregating, storing, handling, transporting, and disposing of all waste — hazardous and non-hazardous — generated at True East Mining Company (TEMC) sites. This procedure ensures strict compliance with ISO 14001:2015 (Clauses 6.1.2 Environmental Aspects, 8.1 Operational Planning and Control), ISO 45001:2018 (Clause 8.1.2), NCEC regulations, and the Saudi Waste Management Law, while minimising environmental impact and actively promoting the waste hierarchy (Reduce, Reuse, Recycle, Recover, Dispose).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>2. Scope</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>This procedure applies to all waste generated by TEMC operations — diamond drilling, exploration, workshops, offices, core yards, and remote desert camps — and by contractors and subcontractors working on behalf of the Company. It covers hazardous waste (used oil, batteries, chemicals, contaminated materials) and non-hazardous waste (general trash, scrap metal, clean drill cuttings, food waste).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>3. Definitions and Abbreviations</p>

            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Term / Abbreviation</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Definition</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Hazardous Waste</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Waste that poses a substantial threat to human health or the environment due to its ignitability, corrosivity, reactivity, toxicity, or formal listing by NCEC regulations.</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Non-Hazardous Waste</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Solid, liquid, or semi-solid waste from industrial or administrative operations that does not exhibit hazardous characteristics (office paper, food waste, scrap wood, clean packaging).</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Authorised Contractor</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>A specialised company formally licensed by NCEC to collect, transport, treat, and dispose of hazardous waste at approved facilities.</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Waste Manifest</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Formal document accompanying every hazardous waste shipment, signed by generator, transporter, and disposal facility.</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Used / Engine Oil</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Petroleum-based or synthetic lubricating oil contaminated during use (drill rigs, generators, vehicles); classified as hazardous waste in KSA.</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>NCEC / PME</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>National Center for Environmental Compliance / Presidency of Meteorology and Environment (predecessor to NCEC).</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>3R</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Waste Hierarchy — Reduce, Reuse, Recycle.</td>
                </tr>
                </tbody>
              </table>
            </div>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>4. Responsibilities</p>

            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Role</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Responsibilities</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Managing Director</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Provides resources for waste infrastructure; approves authorised waste contractor selection; reviews waste performance at Management Review.</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager / Safety Officer</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Administers the waste management system; ensures classification, segregation, and storage compliance; coordinates with authorised contractors; maintains manifests; reports to NCEC when legally required.</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Site Supervisors / Shift In-Charge</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Ensure daily segregation and safe storage at the site level; enforce 3R practices; report spills and non-compliance immediately.</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>All Employees &amp; Contractors</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Segregate waste at the source; follow handling rules; report hazards and spills immediately.</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Authorised Waste Contractor</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Collects, transports, and disposes of waste strictly per their NCEC licence; provides official Waste Manifests back to TEMC.</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Management Representative</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Reviews overall waste performance at Management Review Meetings; drives continual environmental improvement.</td>
                </tr>
                </tbody>
              </table>
            </div>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>5. General Safety Rules and Waste Hierarchy</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>Waste is any substance discarded or no longer useful that cannot be put to direct beneficial use. All operations apply the following hierarchy:</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Reduce — minimise generation at the source through careful planning, efficient use of materials, and bulk purchasing.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Reuse — reuse materials where safe and practical (e.g. drums for non-hazardous storage, timber for shuttering).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Recycle — segregate metals, paper, plastics, and oils for recycling via approved contractors.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Recover — recover energy from waste where applicable.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Dispose — landfill or destruction is the last resort, via an NCEC-licensed facility.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Segregation: never mix hazardous and non-hazardous waste under any circumstances.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Spill response: report leaks and spills immediately. Contain and clean using designated spill kits.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• PPE: all personnel wear appropriate PPE when handling waste — nitrile gloves, safety goggles, coveralls, and safety boots.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>6. Waste Classification</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>Waste is classified as hazardous if it exhibits any of the following characteristics (per NCEC criteria):</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Ignitability — flash point &lt;60°C or spontaneously combustible.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Corrosivity — pH ≤2 or ≥12.5, or corrodes steel.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Reactivity — unstable, explosive, or generates toxic gases when mixed with water or heated.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Toxicity — harmful or fatal if absorbed, ingested, or inhaled.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>TEMC mining examples: used oil and lubricants, batteries, chemical residues, contaminated rags, oily water, and drill cuttings heavily contaminated with hydrocarbons.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>7. Hazardous Waste Storage</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Containers — use appropriate, labelled containers — UN-approved drums for liquids.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Fill Limits — fill liquid containers to a maximum of 95% capacity to allow headspace for thermal expansion.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Segregation — physically segregate chemically incompatible wastes (acids must be stored separately from bases; oxidisers separate from organics).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Bunding — store all hazardous liquids in a designated, secure, bunded area with secondary containment capable of holding 110% of the largest container's volume.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Environment — the storage area is clean, well-ventilated, located away from ignition sources, and equipped with spill kits and signage &quot;DANGER – Hazardous Waste – No Unauthorised Access&quot;.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Batteries — store used lead-acid batteries upright in a dry, covered area protected from direct desert sunlight.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Inspections — the HSE team inspects hazardous waste storage areas weekly and records findings.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• 90-Day Limit — hazardous waste shall not be stored on site longer than 90 days before being removed by an authorised contractor, unless a longer period is specifically authorised by NCEC.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>8. Handling and Disposal of Hazardous Waste</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Collection: waste collected at the source in labelled containers.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Internal transport: waste transported to the central storage area by trained personnel only.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• External transport: only an NCEC-licensed waste contractor is engaged for off-site transport and disposal.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Documentation: a formal Waste Manifest is completed for every shipment, signed by the generator, transporter, and final disposal facility.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Retention: all Waste Manifests retained in the IMS for a minimum of 5 years.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Regulatory reporting: the HSE Manager reports to NCEC when unexpectedly large volumes are generated or a reportable environmental spill occurs.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>9. Non-Hazardous Waste Management</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>Mining examples: office paper, food waste, scrap wood, metal scrap, clean packaging, exhausted tyres, empty non-hazardous containers, general garbage, and clean (non-contaminated) drill cuttings.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Source Segregation — clearly labelled, colour-coded bins at the source (Paper Only, General Waste, Scrap Metal, Plastics).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Storage — temporarily store non-hazardous waste in a designated, fenced area to prevent wind-blown litter.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Collection — arrange regular collection by municipal authorities or an authorised general waste contractor.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Prohibitions — no open burning or unauthorised dumping of waste is allowed on any TEMC site. Breach is a disciplinary matter.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>10. Record Keeping and Monitoring</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Waste Register: maintain a live Waste Register tracking waste types, volumes generated, disposal dates, and manifest numbers.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Monthly reporting: waste metrics summarised in the Monthly HSE Report.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Manifest reconciliation: every issued manifest is reconciled against the disposal certificate.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>11. Performance Indicators</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>[NEEDS CEO REVIEW — targets indicative]</p>

            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>KPI</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Target</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Frequency</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Hazardous / non-hazardous segregation compliance</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>100%</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Weekly</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Waste manifests returned from disposal facility</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>100%</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Monthly</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Hazardous waste storage duration</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>≤ 90 days</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Monthly</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Recycling rate of non-hazardous waste</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>≥ 30%</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Quarterly</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Reportable environmental spills</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>0</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Monthly</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Weekly hazardous waste area inspections completed</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>100%</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Weekly</td>
                </tr>
                </tbody>
              </table>
            </div>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>12. Continual Improvement</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• This procedure is reviewed annually, or immediately following any environmental incident or non-conformity.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• The 3R culture is promoted through targeted Toolbox Talks (PROC-HSE-007).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Quarterly internal audits of waste storage areas, bin segregation accuracy, and disposal records are conducted by the HSE Manager.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Waste performance is reported at Management Review (PROC-SYS-002).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>13. References</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• ISO 14001:2015 — Environmental Management Systems, Clauses 6.1.2 Environmental Aspects, 8.1 Operational Planning and Control.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• ISO 45001:2018 — Clause 8.1.2 Eliminating Hazards and Reducing OH&amp;S Risks.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• NCEC — Hazardous Waste Management Regulations (KSA).</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• Saudi Waste Management Law — National framework for waste reduction and disposal.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• MHRSD — Occupational Safety Requirements for Waste Handling.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>• TEMC PROC-HSE-007 Toolbox Talks; PROC-HSE-003 Hazard Identification and Risk Assessment; PROC-SYS-002 Management Review; PROC-SYS-008 Corrective Action.</p>

            <p className="text-sm leading-relaxed mb-3" style={{ color: "#081C2E" }}>14. Records Retention</p>

            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Record</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Owner</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Retention</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Waste Manifests</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>5 years</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Waste Register</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Live + 5 years archive</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Hazardous waste area inspection records</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>3 years</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Contractor NCEC licence copies</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Live + 3 years after expiry</td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Monthly HSE waste reports</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>5 years</td>
                </tr>
                </tbody>
              </table>
            </div>

            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Rev</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Date</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Description of Changes</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Author</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>00</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>01.03.2026</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Initial release</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Abduljawad Bouguelta</td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>01</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>10.04.2026</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Rebuilt to TE design standard; preserved all original content (waste hierarchy, classification criteria, 95% fill / 110% bunding rules, NCEC-licensed contractor requirement, manifest process); added responsibilities table, 90-day storage limit, KPI table with CEO review flag, records retention table, explicit linkage to PROC-SYS-002 and PROC-HSE-007.</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>HSE Manager</td>
                </tr>
                </tbody>
              </table>
            </div>

            <div className="overflow-x-auto mb-6 rounded border" style={{ borderColor: "#dde3ec" }}>
              <table className="w-full text-sm border-collapse">
                <thead style={{ backgroundColor: "#081C2E" }}>
                  <tr>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Role</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Name</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Signature</th>
                  <th className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider" style={{ color: "#C49A28" }}>Date</th>
                  </tr>
                </thead>
                <tbody>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Prepared by (HSE Manager)</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                </tr>
                <tr >
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Reviewed by (QA / MR)</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                </tr>
                <tr style={{ backgroundColor: "rgba(8,28,46,0.03)" }}>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}>Approved by (Managing Director / CEO)</td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                  <td className="px-3 py-2 text-xs" style={{ color: "#081C2E" }}></td>
                </tr>
                </tbody>
              </table>
            </div>
        </div>
      </div>
    </Layout>
  );
}
