CREATE TABLE `near_miss_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` varchar(32) NOT NULL,
	`status` enum('submitted','under_review','closed') NOT NULL DEFAULT 'submitted',
	`dateOfOccurrence` varchar(20) NOT NULL,
	`timeOfOccurrence` varchar(10),
	`location` text,
	`departmentSite` text,
	`reportedBy` text NOT NULL,
	`employeeId` varchar(64),
	`classification` text,
	`classificationOther` text,
	`description` text NOT NULL,
	`contributingFactors` text,
	`contributingFactorsOther` text,
	`potentialSeverity` varchar(20),
	`potentialLikelihood` varchar(20),
	`correctiveActions` text,
	`supervisorName` text,
	`supervisorDate` varchar(20),
	`hseOfficerName` text,
	`hseOfficerDate` varchar(20),
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`sheetSynced` int DEFAULT 0,
	CONSTRAINT `near_miss_submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `near_miss_submissions_submissionId_unique` UNIQUE(`submissionId`)
);
